# Generated by Django 4.1.7 on 2024-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherAdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='description',
            field=models.CharField(default='this is  data structure course', max_length=300),
            preserve_default=False,
        ),
    ]
