# Generated by Django 4.1.7 on 2024-02-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherAdminPanel', '0002_coursename_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=2)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherAdminPanel.studentstatus')),
            ],
        ),
    ]
