# Generated by Django 4.1.7 on 2024-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phd', models.CharField(max_length=100)),
                ('masters', models.CharField(max_length=100)),
                ('bachelor', models.CharField(max_length=100)),
            ],
        ),
    ]
